server {
    listen 8080;
    server_name localhost;
    client_max_body_size 5M;

    root /usr/share/nginx/html;
    index index.html;

    # SPA routing - redirect all 404s to index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
